docker:
  image: tannakartikey/currents
assets:
  id_rsa: "tannakartikey/currents_private#currents.heroku"
  id_rsa.pub: "tannakartikey/currents_private#currents.heroku.pub"
env:
  RAILS_ENV: "test"
  DISPLAY: ":99"
  CURRENTS_DB_NAME: "currents_test"
  CURRENTS_PSQL_USERNAME: "currents"
  CURRENTS_PSQL_PASSWORD: "currents"
  CODECLIMATE_REPO_TOKEN: "6baff733d54da0d4301ea7e9e9f4601e10ce557b6601523271df4ea9a08fc3c3"
install: |-
  git config --global user.email "hello@thefishing.network"
  git config --global user.name "currents-network"
merge:
  script: |-
    bundle install
    rake
  fast-froward: no
release:
  script: |-
    git remote add heroku git@heroku.com:currents-dev.git
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git push -f heroku $(git symbolic-ref --short HEAD):master
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://thefishing.network > /dev/null
  commanders:
  - tannakartikey
  - ajc113
deploy:
  script: |-
    sudo chown -R r:r /usr/local
    bundle install
    sudo /etc/init.d/postgresql start
    rake db:create
    xvfb-run rake
    git remote add heroku git@heroku.com:currents-kt.git
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git push -f heroku master:master
  commanders:
  - tannakartikey
  - ajc113
architect:
- tannakartikey
- ajc113
