docker:
  image: tannakartikey/currents
assets:
  id_rsa: "tannakartikey/currents_private#currents.heroku"
  id_rsa.pub: "tannakartikey/currents_private#currents.heroku.pub"
  kartikey_heroku: "tannakartikey/currents_private#tannakartikey.heroku"
  kartikey_heroku.pub: "tannakartikey/currents_private#tannakartikey.heroku.pub"
  application.yml: "tannakartikey/currents_private#config/application.yml"
env:
  RAILS_ENV: "test"
  DISPLAY: ":99"
install: |-
  sudo /etc/init.d/postgresql start
  sudo chown -R r:r /usr/local
  cp ../application.yml config/application.yml
  bundle install
  rake db:create
  sleep 20
  xvfb-run rake
  git config --global user.email "hello@thefishing.network"
  git config --global user.name "currents-network"
  wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
merge:
  fast-froward: no
release:
  script: |-
    git remote add heroku git@heroku.com:currents.git
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ../kartikey_heroku.pub ../kartikey_heroku ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git push -f heroku $(git symbolic-ref --short HEAD):master
    heroku run rake db:migrate --app currents
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://thefishing.network > /dev/null
  commanders:
  - tannakartikey
  - ajc113
deploy:
  script: |-
    git remote add heroku git@heroku.com:currents-dev.git
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ../kartikey_heroku.pub ../kartikey_heroku ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git push -f heroku master:master
    heroku run rake db:migrate --app currents-dev
  commanders:
  - tannakartikey
  - ajc113
architect:
- tannakartikey
- ajc113
