docker:
  image: tannakartikey/currents
  as_root: true
assets:
  id_rsa: "tannakartikey/currents_private#currents.heroku"
  id_rsa.pub: "tannakartikey/currents_private#currents.heroku.pub"
  kartikey_heroku: "tannakartikey/currents_private#tannakartikey.heroku"
  kartikey_heroku.pub: "tannakartikey/currents_private#tannakartikey.heroku.pub"
  application.yml: "tannakartikey/currents_private#config/application.yml"
  netrc: "tannakartikey/currents_private#netrc"
  curlrc: "tannakartikey/currents_private#curlrc"
env:
  RAILS_ENV: "test"
  DISPLAY: ":99"
install: |-
  sudo /etc/init.d/postgresql start
  cp ../application.yml config/application.yml
  bundle install
  rake db:create
  sleep 20
  xvfb-run rake
  git config --global user.email "hello@thefishing.network"
  git config --global user.name "currents-network"
  git config --global core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  mv ../curlrc ../.curlrc
  mv ../netrc ../.netrc
  curl --silent --output /dev/null https://api.heroku.com/apps
merge:
  fast-froward: no
release:
  script: |-
    heroku pg:backups:capture --app currents
    git remote add heroku git@heroku.com:currents.git
    mkdir /root/.ssh
    mv ../id_rsa ../id_rsa.pub ../kartikey_heroku.pub ../kartikey_heroku /root/.ssh
    chmod -R 600 /root/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > /root/.ssh/config
    git push -f heroku $(git symbolic-ref --short HEAD):master
    heroku run rake db:migrate --app currents
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://thefishing.network > /dev/null
  commanders:
  - tannakartikey
  - ajc113
deploy:
  script: |-
    heroku pg:backups:capture --app currents-dev
    git remote add heroku git@heroku.com:currents-dev.git
    mkdir /root/.ssh
    mv ../id_rsa ../id_rsa.pub ../kartikey_heroku.pub ../kartikey_heroku /root/.ssh
    chmod -R 600 /root/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > /root/.ssh/config
    git push -f heroku master:master
    heroku run rake db:migrate --app currents-dev
  commanders:
  - tannakartikey
  - ajc113
architect:
- tannakartikey
- ajc113
