docker:
  image: tannakartikey/currents
assets:
  id_rsa: "tannakartikey/currents_private#currents.heroku"
  id_rsa.pub: "tannakartikey/currents_private#currents.heroku.pub"
install: |-
  #sudo apt-get install -y postgresql
  #sudo /etc/init.d/postgresql start
  #sudo -u postgres -- sh -c "psql --command 'CREATE USER currents WITH SUPERUSER PASSWORD \'currents\'"
  #sudo -u  postgres -- sh -c "createdb currents_test --owner currents"
  git config --global user.email "hello@thefishing.network"
  git config --global user.name "currents-network"
merge:
  script: |
    bundle install
    rake
  fast-froward: no
release:
  script: |
    bundle install
    rake
    git remote add heroku git@heroku.com:currents-dev.git
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git push -f heroku $(git symbolic-ref --short HEAD):master
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://thefishing.network > /dev/null
  commanders:
  - tannakartikey
  - ajc113
deploy:
  script: |
    bundle install
    rake
    git remote add heroku git@heroku.com:currents-kt.git
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git push -f heroku master:master
  commanders:
  - tannakartikey
  - ajc113
architect:
- tannakartikey
- ajc113
