language: ruby
before_script:
- psql -c 'create database travis_ci_test' -U postgres
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
addons:
  code_climate:
    repo_token: 6baff733d54da0d4301ea7e9e9f4601e10ce557b6601523271df4ea9a08fc3c3
after_success:
- bundle exec codeclimate-test-reporter
services:
- postgresql
env:
  matrix:
  - CURRENTS_DB_NAME=travis_ci_test CURRENTS_PSQL_USERNAME=postgres CURRENTS_PSQL_PASSWORD=''
    CODECLIMATE_REPO_TOKEN=6baff733d54da0d4301ea7e9e9f4601e10ce557b6601523271df4ea9a08fc3c3
  global:
  - secure: dm9HwNexOlDPhznr50IHPDeZdVBs1E/hzFrSRDvcaGYk/40HAATecxTNTp+Db7O9LWIdQ4y9b/k81ZAT4DEsTZFsDNBC/9RjrlLgb7En7ExFkbkx4bmfsqxrHiVsPjmsyPbatyFzUmHAzQ03FE5KNAmGqKLd3bhtWIpbcJVwLJHIHaQ730Lo2t0xsOgLvPz5vxESGaFGqwcGRSqqQ5ktUiT9aYqFww70MAYbFnZ2rNZm7kKYgqUxVmjZTpHu2lSHaKWML5vFd9vkTfk81EHbgFWH5hQkbqaAzfbLyFQXsNzr3AWid06g3lNT9/NrCvpe6TzReNUK7xFt8FqBA7HiiHNp0sMW9W0Z6QII7cVJazIoI13kSMM1iYYBkosu68qfmVuDltPTq4rpKSbFvlpTnN6Frf6DSTR7jYezr38VCrwJldu2JtQfu7zOuKz0X87f0xyYNb38vgBJVxIm9jQUDhgautvf15Z0HZytyoUa+Xk2uZhyEmGujbHwB+EmXaGI2qnGNhGcpJSffFYE+Lvrl7k+zSyQSincZaJTfh1vNv0/jPCR+PsB/uKSPZDPX+UIplvdd+3BZbULJk2NyS1pCaKvXVux39U7ahfeV/jKXoZGilaeHp8GBA8eLjjKz+Z8THgTi5SUipj+zhUzmtNKrPrTchEYBG4gb/gsUtc72Rg=
  - secure: QkdwOQoO8kVw/RHDLUxO5/f21pS+6M/sVhNlryRSyT+Qa8KtavY5cUCmUPo27Sov5oMS1lopO6urqkvtDOENNSVG28YTnCUVPsItmSIvmxCF6EzAurheW6DkjxEB1saTzHaK1GRLHksj+1z7RIt/964vrnUUXPzsaX0d6I4LX5uyvuXyC3Dq1mC4uESKZ7fsCnjRo0BS8zHJIIHK7Olj0FLLGoZHzjYejBLxRETzJtOW27dC4Zcqb1Ua3oIKYyrKYC7t+EBJCBJ2hL+faKGtZBF2NWICtcoU1h5wWnT2CKFULpwd2a61quFXXBr0DHEcowGiSRyGQ+4u7qls77fELi5O+KcRxl/vn52dIbk1YRJtdeFrhhxl/LqqiSg2GCETnLgQf00TxwtZpikt6XR7EExzQIXAPL6KYiZF/umQGI9fVPbEuO4KTGekJsr/UgmKSAWb0xzGlcueK/2uRirYBjhxe3pAEYkygKyqalvqtI1H6mhCHH/fBN2BMf+JWxm1WHB5O6HNWcs0ULHCUVfKoXE0CpuCqdMjxzYOtOt5TvHW6uBm34o0xGsX90X/EjWVTNRbBnpbsQc6LDMoYIXfTkALq74rvshM+gBarYEu/z/6eUNCbn2uBCpBfH9PU63bjl0SF8FBE36RK36DzQEboeI8H9Al9uTYMDRSCKwwNDA=
notifications:
  slack:
    secure: b8p9Ebwocr/qaU6Ry/0wxIyUwiy/9NxyK5ePtAVZeQkBVbWrwJDEhwN0uHKngbqiLOr/w8D7e1/6g3UW2QEEmXRM7RCHKf7Q7vKqjhwc8qVybbUNKvYfAZ/xbQODZ5xHLyf6VXfXHQ1O9trwzCquAK29A8SurxoeuF3xHhdMvxqFdE6a6FYv/F49WWAUSPaGYPCW1pIytAYafERzf/OqyIHu6G2ZWO/pAJzxFrga1doZeBeNc73S559IcMhjpsC21XNzJ6iRs3mT2Qt8OcgYQploo/GgKz5xlK/JR2/H0ovvmBBQHv7CBEPZKnGT4rThRcEVLYi+hiW9dZ0S+bu8AJSXwH5vUj71Gz/H9+gh+57TZ5JyObXiwU1nV6ksLfO6ez50TzrjDHxYyRWm1HD6Izf6fG5jJYPYkN/GiFNjsyCYuwzTpSjq6rkL7lR9ah8W+GXYDvZvlqIy38q4eGyAcnirhiH92B6Mtc3fkbuKiViPD9eS+tTrO6rJTveHZc/fk7BiY9SS8k64/HN7wdKkpAzem62Bce13vo2yFKsdjpPxFMfNjVWW7hwpqRRzhYzYXLMcSfN3bGVDWLJxVLKPjXhWp97BVv50Q6vhGCen3ozD9RuDJ40xmobkUr6t+rXsCnppdz8HyvFaTVh6Q6SYPg8Yz37bY6N1h35YvW3Wht0=
