language: ruby
before_script:
- psql -c 'create database travis_ci_test' -U postgres
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
addons:
  code_climate:
    repo_token: 6baff733d54da0d4301ea7e9e9f4601e10ce557b6601523271df4ea9a08fc3c3
after_success:
- bundle exec codeclimate-test-reporter
services:
- postgresql
env:
  matrix:
  - CURRENTS_DB_NAME=travis_ci_test CURRENTS_PSQL_USERNAME=postgres CURRENTS_PSQL_PASSWORD=''
    CODECLIMATE_REPO_TOKEN=6baff733d54da0d4301ea7e9e9f4601e10ce557b6601523271df4ea9a08fc3c3
notifications:
  slack:
    secure: b8p9Ebwocr/qaU6Ry/0wxIyUwiy/9NxyK5ePtAVZeQkBVbWrwJDEhwN0uHKngbqiLOr/w8D7e1/6g3UW2QEEmXRM7RCHKf7Q7vKqjhwc8qVybbUNKvYfAZ/xbQODZ5xHLyf6VXfXHQ1O9trwzCquAK29A8SurxoeuF3xHhdMvxqFdE6a6FYv/F49WWAUSPaGYPCW1pIytAYafERzf/OqyIHu6G2ZWO/pAJzxFrga1doZeBeNc73S559IcMhjpsC21XNzJ6iRs3mT2Qt8OcgYQploo/GgKz5xlK/JR2/H0ovvmBBQHv7CBEPZKnGT4rThRcEVLYi+hiW9dZ0S+bu8AJSXwH5vUj71Gz/H9+gh+57TZ5JyObXiwU1nV6ksLfO6ez50TzrjDHxYyRWm1HD6Izf6fG5jJYPYkN/GiFNjsyCYuwzTpSjq6rkL7lR9ah8W+GXYDvZvlqIy38q4eGyAcnirhiH92B6Mtc3fkbuKiViPD9eS+tTrO6rJTveHZc/fk7BiY9SS8k64/HN7wdKkpAzem62Bce13vo2yFKsdjpPxFMfNjVWW7hwpqRRzhYzYXLMcSfN3bGVDWLJxVLKPjXhWp97BVv50Q6vhGCen3ozD9RuDJ40xmobkUr6t+rXsCnppdz8HyvFaTVh6Q6SYPg8Yz37bY6N1h35YvW3Wht0=
    slack: ajcosta:qJt25QAEBAoHlZjMCBrMcO0M
