Location.create!([
  {short_name: "07. Cape Cod - Peaked Hill Bar", long_name: "Peaked Hill Bar down to golfball", coordinates: [], coordinate_file: "53_ph.json"},
  {short_name: "06. Cape Cod Backside", long_name: "Golfball , backside beaches down to nauset inlet", coordinates: [], coordinate_file: "54_backside.json"},
  {short_name: "03. Stellwagen Bank - (SWC) South West Corner", long_name: "The notch south to the sw corner", coordinates: [], coordinate_file: "56_sw_swc.json"},
  {short_name: "04. Stellwagen Bank - (SEC) South East Corner", long_name: "Middle bank east to the edge", coordinates: [], coordinate_file: "58_sw_sec.json"},
  {short_name: "02. Stellwagen Bank - Middlebank", long_name: "Middlebank south to the notch", coordinates: [], coordinate_file: "59_sw_middle.json"},
  {short_name: "01. Stellwagen Bank - (NWC) Northwest Corner", long_name: "Northwest Corner of Stellwagen Bank south to middlebank covering the western edge to middlebank.", coordinates: [], coordinate_file: "60_sw_nwc.json"},
  {short_name: "08. Cape Cod - Race Point", long_name: "Race Point, Bathhouse to Wood End", coordinates: [], coordinate_file: "62_race.json"},
  {short_name: "09. Cape Cod - Provincetown", long_name: "Provincetown Harbor to Pamet River", coordinates: [], coordinate_file: "63_ptown.json"},
  {short_name: "10. Cape Cod - Billingsgate Shoals", long_name: "Billingsgate shoals, The path south to Brewster flats", coordinates: [], coordinate_file: "64_shoals.json"},
  {short_name: "11. Cape Cod - Wellfleet Harbor", long_name: "Wellfleet Harbor to Brewster Flats", coordinates: [], coordinate_file: "66_welfleet.json"},
  {short_name: "16. South Shore - Plymouth Bay", long_name: "Plymouth, Duxbury, and Kingston Bays", coordinates: [], coordinate_file: "67_plymouth.json"},
  {short_name: "15. Cape Cod Canal", long_name: "The Ditch", coordinates: [], coordinate_file: "68_canal.json"},
  {short_name: "13. Cape Cod Bay - (SW )Southwest", long_name: "PowerPlant , Manomet and White Cliffs down to canal", coordinates: [], coordinate_file: "69_ccb_sw.json"},
  {short_name: "12. Cape Cod Bay - South", long_name: "Canal, Scorton Creek to Barnstable, including the Fingers", coordinates: [], coordinate_file: "70_ccb_south.json"},
  {short_name: "14. Cape Cod Bay - (NW ) Northwest", long_name: "Green Harbor south to the PowerPlant.  Included Farnham, High Pines Ledge and the Gurnet.", coordinates: [], coordinate_file: "71_ccb_northwest.json"},
  {short_name: "17. South Shore - Scituate", long_name: "BrantRock, North River, Scituate, to Minots including offshore ledges", coordinates: [], coordinate_file: "72_scituate.json"},
  {short_name: "18. Boston - Inner Harbor", long_name: "Boston Harbor out to Dear Island, Pt Allerton", coordinates: [], coordinate_file: "73_boston_inner.json"},
  {short_name: "19. Boston - Outer Harbor", long_name: "Boston Outer Harbor to  Nahant Bay, offshore ledges down to the glades.", coordinates: [], coordinate_file: "75_boston_outer.json"},
  {short_name: "05. Stellwagen Bank - Eastside", long_name: "Waters east of middlebank out to WildCat Knoll", coordinates: [], coordinate_file: "sw_eastside.json"},
  {short_name: "25. Cape Cod - Chatham", long_name: "Nauset Inlet to Chatham Harbor out to the 3 mile line", coordinates: [], coordinate_file: "84_Chatham.json"},
  {short_name: "22. Cape Cod - Whiting Grounds", long_name: "Whiting Grounds to to the gulley", coordinates: [], coordinate_file: "85_whiting_grounds.json"},
  {short_name: "20. North Shore", long_name: "Marblehead, Salem Sound, Gloucester to Thatcher Island", coordinates: [], coordinate_file: "86_north_shore.json"},
  {short_name: "21. North Shore - Merrimack", long_name: "Halibut Point, Plum island north to the Merrimack.", coordinates: [], coordinate_file: "87_north_shore_north.json"},
  {short_name: "23. Jeffreys Ledge - West", long_name: "West portion of Jeffreys Ledge", coordinates: [], coordinate_file: "88_jefferies_west.json"},
  {short_name: "24. Jeffreys Ledge - East", long_name: "Eastern portions of Jeffreys Ledge", coordinates: [], coordinate_file: "89_jefferies_east.json"},
  {short_name: "26. Cape Cod - Monomoy", long_name: "Monomoy Shoals", coordinates: [], coordinate_file: "90_monomoy.json"},
  {short_name: "27. Cape Cod - Nantucket Sound East", long_name: "Eastern Nantucket sound out to Monomoy.  Hyanis south to Muskeget Island", coordinates: [], coordinate_file: "91_Nantucket_S_East.json"},
  {short_name: "28. Cape Cod - Nantucket Sound West", long_name: "Western Nantucket sound from Falmouth to Hyannis south to Cape Poge.  Includes hedge fence, and horseshoe shoals.", coordinates: [], coordinate_file: "92_nantucket_sound_west.json"},
  {short_name: "29. Vineyard Sound", long_name: "Vineyard Sound  and Elizabeth islands including Quick's, Robinson's, and Wood's hole.  Cuttyhunk to Falmouth.", coordinates: [], coordinate_file: "93_vineyard_sound.json"},
  {short_name: "31. Buzzards Bay - East", long_name: "Mass Maritime west to Mattapoisett.  Includes Onset, Wareham, Marion, Pocasset, and North Falmouth.", coordinates: [], coordinate_file: "94_buzzbay_east.json"},
  {short_name: "30. Buzzards Bay - West", long_name: "Westport east to New Bedford.  Includes Dartmouth, Cuttyhunk, and Gosnold, Naushon Island.", coordinates: [], coordinate_file: "95_buzzbay_west.json"}
])
